// This file was generated by nightwatch-types-generator
import { ImageLandingPage, LandingPage } from '../nightwatch/page-objects'
import { BingPage } from '../nightwatch/pageObjects'
import '@nightwatch/apitesting'
import 'nightwatch-saucelabs-endsauce'
import 'nightwatch'

declare module 'nightwatch' {
  export interface NightwatchCustomPageObjects {
    google: {
      image: {
        imageLandingPage: () => ImageLandingPage
      },
      landingPage: () => LandingPage
    },
    bingPage: () => BingPage
  }
}